# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.18-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /golang-echo-example


##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /golang-echo-example /golang-echo-example

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/golang-echo-example"]