name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Fetch required Go modules
      run: go mod download
    
    - name: Build
      run: go build -v ./...
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with: 
        path: /tmp/.buildx-cache
        key:  ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-buildx-
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push:    false
        load:    true
        tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to:   type=local,dest=/tmp/.buildx-cache

    - name: Test
      run: go test -v ./...
