name: Run CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Fetch required Go modules
      run: go mod download
      
    - name: Build
      run: go build -v ./...
      
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest

    - name: Test
      run: go test -v ./...
